# Generated by Django 5.2.17 on 2026-08-15 00:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("partners", "0001_initial"),
        ("people", "0001_initial"),
        ("results", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerAssertionRevision",
            fields=[
                (
                    "assertion_revision_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve_link", "Approve identity link"),
                            ("relink", "Correct identity link"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "authorization_basis_type",
                    models.CharField(
                        choices=[
                            ("competitor_consent", "Competitor consent"),
                            ("guardian_consent", "Guardian consent"),
                            ("source_data_rights", "Source data rights"),
                            ("show_finalization_policy", "Show finalization policy"),
                        ],
                        max_length=40,
                    ),
                ),
                ("authorization_basis_reference", models.CharField(max_length=240)),
                ("authorization_captured_at", models.DateTimeField()),
                ("source_payload_digest", models.CharField(max_length=64)),
                ("decision_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="career_assertion_revisions",
                        to="partners.partnerorganization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="career_assertion_revisions",
                        to="people.person",
                    ),
                ),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor",
                        to="career.careerassertionrevision",
                    ),
                ),
                (
                    "reconciliation_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="career_assertion_revisions",
                        to="results.reconciliationcase",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_career_assertion_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="career_assertion_revisions",
                        to="results.publishedsourceresult",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "source_result", "revision"],
                        name="career_source_revision_idx",
                    ),
                    models.Index(
                        fields=["person", "created_at"],
                        name="career_person_history_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="career_revision_positive",
                    ),
                    models.UniqueConstraint(
                        fields=("source_result", "revision"),
                        name="unique_career_source_revision",
                    ),
                ],
            },
        ),
    ]
