# Generated by Django 5.2.17 on 2026-08-15 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career", "0001_initial"),
        ("consent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerassertionrevision",
            name="consent_grant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="career_assertion_revisions",
                to="consent.consentgrant",
            ),
        ),
        migrations.AddConstraint(
            model_name="careerassertionrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "authorization_basis_type__in",
                            ("competitor_consent", "guardian_consent"),
                        ),
                        ("consent_grant__isnull", False),
                    ),
                    models.Q(
                        (
                            "authorization_basis_type__in",
                            ("source_data_rights", "show_finalization_policy"),
                        ),
                        ("consent_grant__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="career_authority_evidence_shape",
            ),
        ),
    ]
