# Generated by Django 5.2.17 on 2026-08-15 05:13

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("partners", "0001_initial"),
        ("results", "0003_spreadsheet_source_coordinates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyMigrationRun",
            fields=[
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "run_version",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("ruleset_version", models.CharField(max_length=80)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("configured", "Configured"),
                            ("dry_run_complete", "Dry run complete"),
                            ("approved", "Approved"),
                            ("applying", "Applying"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                            ("failed", "Failed"),
                        ],
                        default="discovered",
                        max_length=32,
                    ),
                ),
                (
                    "plan_digest",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "source_state_digest",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "dry_run_manifest_digest",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("total_sheets", models.PositiveIntegerField(default=0)),
                ("included_sheets", models.PositiveIntegerField(default=0)),
                ("ignored_sheets", models.PositiveIntegerField(default=0)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("candidate_rows", models.PositiveIntegerField(default=0)),
                ("ignored_rows", models.PositiveIntegerField(default=0)),
                ("publishable_rows", models.PositiveIntegerField(default=0)),
                ("quarantined_rows", models.PositiveIntegerField(default=0)),
                ("duplicate_rows", models.PositiveIntegerField(default=0)),
                ("conflict_rows", models.PositiveIntegerField(default=0)),
                ("applied_rows", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_legacy_migration_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_migration_runs",
                        to="partners.partnerorganization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyMigrationJob",
            fields=[
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_kind",
                    models.CharField(
                        choices=[
                            ("dry_run", "Dry run"),
                            ("apply", "Apply"),
                            ("reconcile", "Reconcile"),
                            ("withdraw", "Withdraw"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "job_sequence",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("interrupted", "Interrupted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("next_checkpoint_sequence", models.PositiveIntegerField(default=1)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("last_error_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_legacy_migration_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_migration_jobs",
                        to="partners.partnerorganization",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="legacy_migration.legacymigrationrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyMigrationDecisionRevision",
            fields=[
                (
                    "decision_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approve", "Approve"), ("withdraw", "Withdraw")],
                        max_length=16,
                    ),
                ),
                (
                    "manifest_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("rationale", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_migration_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_migration_decisions",
                        to="partners.partnerorganization",
                    ),
                ),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor",
                        to="legacy_migration.legacymigrationdecisionrevision",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision_revisions",
                        to="legacy_migration.legacymigrationrun",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "decision_id"),
                "abstract": False,
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.CreateModel(
            name="LegacySourceInventory",
            fields=[
                (
                    "inventory_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_namespace",
                    models.CharField(default="legacy-results", max_length=120),
                ),
                ("source_key", models.CharField(max_length=200)),
                ("data_rights_reference", models.CharField(max_length=240)),
                ("parser_version", models.CharField(max_length=80)),
                (
                    "manifest_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_source_inventory",
                        to="results.sourceartifact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_legacy_source_inventories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_source_inventories",
                        to="partners.partnerorganization",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.AddField(
            model_name="legacymigrationrun",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="migration_runs",
                to="legacy_migration.legacysourceinventory",
            ),
        ),
        migrations.CreateModel(
            name="LegacyTablePlan",
            fields=[
                (
                    "table_plan_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=160)),
                (
                    "header_row",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "start_row",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "end_row",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "start_column",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "end_column",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("mapping_rules", models.JSONField(default=dict)),
                (
                    "mapping_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_legacy_table_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_table_plans",
                        to="partners.partnerorganization",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="table_plans",
                        to="legacy_migration.legacymigrationrun",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "worksheet__sheet_index",
                    "start_row",
                    "start_column",
                    "table_plan_id",
                ),
                "abstract": False,
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.CreateModel(
            name="LegacyMigrationRowPreview",
            fields=[
                (
                    "preview_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_sheet_index", models.PositiveIntegerField()),
                (
                    "source_row_number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "source_column_start",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "source_column_end",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("canonical_payload", models.JSONField(default=dict)),
                (
                    "payload_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("publishable", "Publishable"),
                            ("quarantined", "Quarantined"),
                            ("duplicate", "Duplicate"),
                            ("conflict", "Conflict"),
                            ("ignored", "Ignored"),
                        ],
                        max_length=20,
                    ),
                ),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                (
                    "source_state_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_migration_row_previews",
                        to="partners.partnerorganization",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="row_previews",
                        to="legacy_migration.legacymigrationrun",
                    ),
                ),
                (
                    "table_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="row_previews",
                        to="legacy_migration.legacytableplan",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "source_sheet_index",
                    "source_row_number",
                    "source_column_start",
                    "preview_id",
                ),
                "abstract": False,
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.CreateModel(
            name="LegacyWorksheetPlan",
            fields=[
                (
                    "worksheet_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sheet_index", models.PositiveIntegerField()),
                ("sheet_name", models.CharField(max_length=255)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("visible", "Visible"),
                            ("hidden", "Hidden"),
                            ("very_hidden", "Very hidden"),
                        ],
                        default="visible",
                        max_length=16,
                    ),
                ),
                ("max_row", models.PositiveIntegerField(default=0)),
                ("max_column", models.PositiveIntegerField(default=0)),
                (
                    "disposition",
                    models.CharField(
                        choices=[("included", "Included"), ("ignored", "Ignored")],
                        max_length=16,
                    ),
                ),
                ("ignore_reason", models.CharField(blank=True, max_length=240)),
                (
                    "metadata_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("header_candidates", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_worksheet_plans",
                        to="partners.partnerorganization",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worksheets",
                        to="legacy_migration.legacymigrationrun",
                    ),
                ),
            ],
            options={
                "ordering": ("sheet_index", "worksheet_id"),
                "abstract": False,
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.AddField(
            model_name="legacytableplan",
            name="worksheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="table_plans",
                to="legacy_migration.legacyworksheetplan",
            ),
        ),
        migrations.CreateModel(
            name="LegacyMigrationCheckpoint",
            fields=[
                (
                    "checkpoint_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "first_source_row",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "last_source_row",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "checkpoint_digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("committed", "Committed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("published_rows", models.PositiveIntegerField(default=0)),
                ("quarantined_rows", models.PositiveIntegerField(default=0)),
                ("duplicate_rows", models.PositiveIntegerField(default=0)),
                ("conflict_rows", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ingestion_run",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_migration_checkpoint",
                        to="results.ingestionrun",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_migration_checkpoints",
                        to="partners.partnerorganization",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkpoints",
                        to="legacy_migration.legacymigrationjob",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkpoints",
                        to="legacy_migration.legacymigrationrun",
                    ),
                ),
                (
                    "table_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkpoints",
                        to="legacy_migration.legacytableplan",
                    ),
                ),
                (
                    "worksheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkpoints",
                        to="legacy_migration.legacyworksheetplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyMigrationManifest",
            fields=[
                (
                    "manifest_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dry_run", "Dry run"),
                            ("reconciliation", "Reconciliation"),
                            ("withdrawal", "Withdrawal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "digest",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a lowercase SHA-256 digest.",
                                regex="^[0-9a-f]{64}$",
                            )
                        ],
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_legacy_migration_manifests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_migration_manifests",
                        to="partners.partnerorganization",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manifests",
                        to="legacy_migration.legacymigrationrun",
                    ),
                ),
            ],
            options={
                "ordering": ("kind", "sequence", "manifest_id"),
                "abstract": False,
                "default_permissions": ("add", "view"),
                "indexes": [
                    models.Index(
                        fields=["organization", "kind", "created_at"],
                        name="legacy_manifest_kind_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "kind", "sequence"),
                        name="uniq_legacy_manifest_seq",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="legacymigrationjob",
            index=models.Index(
                fields=["organization", "status", "created_at"],
                name="legacy_job_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationjob",
            constraint=models.UniqueConstraint(
                fields=("run", "job_kind", "job_sequence"),
                name="uniq_legacy_job_sequence",
            ),
        ),
        migrations.AddIndex(
            model_name="legacymigrationdecisionrevision",
            index=models.Index(
                fields=["organization", "decision", "created_at"],
                name="legacy_decision_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationdecisionrevision",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="uniq_legacy_decision_seq"
            ),
        ),
        migrations.AddIndex(
            model_name="legacysourceinventory",
            index=models.Index(
                fields=["organization", "created_at"], name="legacy_inventory_org_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="legacysourceinventory",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_namespace", "source_key"),
                name="uniq_legacy_source_key",
            ),
        ),
        migrations.AddIndex(
            model_name="legacymigrationrun",
            index=models.Index(
                fields=["organization", "state", "created_at"],
                name="legacy_run_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationrun",
            constraint=models.UniqueConstraint(
                fields=("inventory", "run_version"), name="uniq_legacy_run_version"
            ),
        ),
        migrations.AddIndex(
            model_name="legacymigrationrowpreview",
            index=models.Index(fields=["run", "classification"], name="legacy_preview_class_idx"),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationrowpreview",
            constraint=models.UniqueConstraint(
                fields=("run", "table_plan", "source_row_number"),
                name="uniq_legacy_preview_row",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationrowpreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_column_end__gte", models.F("source_column_start"))),
                name="legacy_preview_col_bounds",
            ),
        ),
        migrations.AddIndex(
            model_name="legacyworksheetplan",
            index=models.Index(
                fields=["organization", "disposition"], name="legacy_sheet_disp_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyworksheetplan",
            constraint=models.UniqueConstraint(
                fields=("run", "sheet_index"), name="uniq_legacy_sheet_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="legacyworksheetplan",
            constraint=models.UniqueConstraint(
                fields=("run", "sheet_name"), name="uniq_legacy_sheet_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="legacytableplan",
            constraint=models.UniqueConstraint(
                fields=("worksheet", "label"), name="uniq_legacy_table_label"
            ),
        ),
        migrations.AddConstraint(
            model_name="legacytableplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_row__gte", models.F("start_row"))),
                name="legacy_table_row_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacytableplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_column__gte", models.F("start_column"))),
                name="legacy_table_col_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacytableplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("header_row__gte", models.F("start_row")),
                    ("header_row__lte", models.F("end_row")),
                ),
                name="legacy_table_header_bounds",
            ),
        ),
        migrations.AddIndex(
            model_name="legacymigrationcheckpoint",
            index=models.Index(
                fields=["run", "status", "sequence"], name="legacy_checkpoint_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationcheckpoint",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="uniq_legacy_checkpoint_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationcheckpoint",
            constraint=models.UniqueConstraint(
                fields=("run", "worksheet", "first_source_row", "last_source_row"),
                name="uniq_legacy_checkpoint_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="legacymigrationcheckpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("last_source_row__gte", models.F("first_source_row"))),
                name="legacy_checkpoint_bounds",
            ),
        ),
    ]
