# Generated by Django 5.2.17 on 2026-08-15 01:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("career", "0001_initial"),
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceSnapshotManifest",
            fields=[
                (
                    "snapshot_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        default="strathmark.evidence-snapshot-source.v1", max_length=80
                    ),
                ),
                ("source_id", models.CharField(max_length=128)),
                ("cutoff", models.DateField()),
                ("captured_at", models.DateTimeField()),
                ("rows", models.JSONField(default=list)),
                ("exclusions", models.JSONField(default=list)),
                ("source_digest", models.CharField(max_length=64)),
                ("request_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_snapshot_manifests",
                        to="partners.partnerorganization",
                    ),
                ),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor",
                        to="export.evidencesnapshotmanifest",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_evidence_snapshot_manifests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "cutoff", "created_at"],
                        name="evidence_snapshot_org_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "source_id"),
                        name="unique_evidence_snapshot_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExportEligibilityRevision",
            fields=[
                (
                    "eligibility_revision_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[("eligible", "Eligible"), ("rejected", "Rejected")],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(max_length=240)),
                ("decision_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "career_assertion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_eligibility_revisions",
                        to="career.careerassertionrevision",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_eligibility_revisions",
                        to="partners.partnerorganization",
                    ),
                ),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor",
                        to="export.exporteligibilityrevision",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_export_eligibility_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "decision", "created_at"],
                        name="export_eligibility_state_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="export_eligibility_revision_positive",
                    ),
                    models.UniqueConstraint(
                        fields=("career_assertion", "revision"),
                        name="unique_export_eligibility_revision",
                    ),
                ],
            },
        ),
    ]
