# Generated by Django 5.2.17 on 2026-08-18

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_key_rotation_jobs"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivilegedInvitation",
            fields=[
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("results_manager", "Results manager"),
                            ("export_reviewer", "Results export reviewer"),
                            ("identity_reviewer", "Identity reviewer"),
                            ("privacy_officer", "Privacy officer"),
                            ("partner_administrator", "Partner administrator"),
                            ("security_administrator", "Security administrator"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("platform", "Platform wide"),
                            ("organization", "Partner organization"),
                        ],
                        max_length=20,
                    ),
                ),
                ("external_evidence_reference", models.CharField(max_length=120)),
                ("secret_digest", models.CharField(max_length=64)),
                ("subject_security_version", models.PositiveIntegerField()),
                ("role_policy_version", models.PositiveSmallIntegerField(default=1)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="privileged_invitations",
                        to="partners.partnerorganization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_privileged_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="privileged_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "request_id"),
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.CreateModel(
            name="PrivilegedRecoveryRequest",
            fields=[
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_evidence_reference", models.CharField(max_length=120)),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("lost_factor", "Lost authenticator"),
                            ("replaced_device", "Replaced device"),
                            ("factor_compromise", "Possible factor compromise"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subject_security_version", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_privileged_recoveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="privileged_recovery_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "request_id"),
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.AlterField(
            model_name="privilegedroleassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("results_manager", "Results manager"),
                    ("export_reviewer", "Results export reviewer"),
                    ("identity_reviewer", "Identity reviewer"),
                    ("privacy_officer", "Privacy officer"),
                    ("partner_administrator", "Partner administrator"),
                    ("security_administrator", "Security administrator"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="PrivilegedRecoveryState",
            fields=[
                (
                    "recovery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="operation_state",
                        serialize=False,
                        to="accounts.privilegedrecoveryrequest",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Waiting for second approver"),
                            ("awaiting_reenrollment", "Waiting for MFA setup"),
                            ("completed", "Privileges restored"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending_approval",
                        max_length=28,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"default_permissions": ("add", "change", "view")},
        ),
        migrations.CreateModel(
            name="PrivilegedRecoveryApproval",
            fields=[
                (
                    "approval_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("evidence_reference_digest", models.CharField(max_length=64)),
                ("approved_subject_security_version", models.PositiveIntegerField()),
                ("approved_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_privileged_recoveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recovery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval",
                        to="accounts.privilegedrecoveryrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("approved_at", "approval_id"),
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.CreateModel(
            name="PrivilegedRoleSuspension",
            fields=[
                (
                    "suspension_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("suspended_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recovery_suspensions",
                        to="accounts.privilegedroleassignment",
                    ),
                ),
                (
                    "recovery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_suspensions",
                        to="accounts.privilegedrecoveryrequest",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restored_role_suspensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("suspended_at", "suspension_id"),
                "default_permissions": ("add", "change", "view"),
            },
        ),
        migrations.CreateModel(
            name="PrivilegedInvitationState",
            fields=[
                (
                    "invitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="operation_state",
                        serialize=False,
                        to="accounts.privilegedinvitation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for acceptance"),
                            ("accepted", "Accepted"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_privileged_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"default_permissions": ("add", "change", "view")},
        ),
        migrations.AddIndex(
            model_name="privilegedinvitation",
            index=models.Index(fields=["subject", "created_at"], name="priv_inv_subject_idx"),
        ),
        migrations.AddIndex(
            model_name="privilegedinvitation",
            index=models.Index(fields=["expires_at"], name="priv_inv_expiry_idx"),
        ),
        migrations.AddConstraint(
            model_name="privilegedinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("organization__isnull", True), ("scope", "platform")),
                    models.Q(("organization__isnull", False), ("scope", "organization")),
                    _connector="OR",
                ),
                name="valid_priv_invitation_scope",
            ),
        ),
        migrations.AddField(
            model_name="privilegedrecoverystate",
            name="restored_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="restored_privileged_recoveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="privilegedrecoveryrequest",
            index=models.Index(fields=["subject", "created_at"], name="priv_recovery_subject_idx"),
        ),
        migrations.AddIndex(
            model_name="privilegedrecoveryrequest",
            index=models.Index(fields=["expires_at"], name="priv_recovery_expiry_idx"),
        ),
        migrations.AddConstraint(
            model_name="privilegedrolesuspension",
            constraint=models.UniqueConstraint(
                condition=models.Q(("restored_at__isnull", True)),
                fields=("assignment",),
                name="unique_active_role_suspension",
            ),
        ),
        migrations.AddConstraint(
            model_name="privilegedrolesuspension",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("restored_at__isnull", True), ("restored_by__isnull", True)),
                    models.Q(("restored_at__isnull", False), ("restored_by__isnull", False)),
                    _connector="OR",
                ),
                name="role_suspension_restore_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="privilegedinvitationstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("accepted_at__isnull", True),
                        ("cancelled_at__isnull", True),
                        ("status", "pending"),
                    ),
                    models.Q(
                        ("accepted_at__isnull", False),
                        ("cancelled_at__isnull", True),
                        ("status", "accepted"),
                    ),
                    models.Q(
                        ("accepted_at__isnull", True),
                        ("cancelled_at__isnull", False),
                        ("status", "cancelled"),
                    ),
                    models.Q(
                        ("accepted_at__isnull", True),
                        ("cancelled_at__isnull", True),
                        ("status", "expired"),
                    ),
                    _connector="OR",
                ),
                name="priv_invitation_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="privilegedinvitationstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cancelled_at__isnull", True), ("cancelled_by__isnull", True)),
                    models.Q(("cancelled_at__isnull", False), ("cancelled_by__isnull", False)),
                    _connector="OR",
                ),
                name="priv_invitation_cancel_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="privilegedrecoverystate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approved_at__isnull", True),
                        ("restored_at__isnull", True),
                        ("status", "pending_approval"),
                    ),
                    models.Q(
                        ("approved_at__isnull", False),
                        ("restored_at__isnull", True),
                        ("status", "awaiting_reenrollment"),
                    ),
                    models.Q(
                        ("approved_at__isnull", False),
                        ("restored_at__isnull", False),
                        ("restored_by__isnull", False),
                        ("status", "completed"),
                    ),
                    models.Q(
                        ("restored_at__isnull", True), ("status__in", ("cancelled", "expired"))
                    ),
                    _connector="OR",
                ),
                name="priv_recovery_state_valid",
            ),
        ),
    ]
